spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://localhost:8889/itemsharingdatabase"
    username: "root"
    password: "{cipher} f2f15c1c5298c2402101e72a015d24c0218003ed711b2669b866956822628318"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    
security:
  basic:
    enabled: false
    
server:
  port: 8082